language: go
go:
  - 1.9
services:
  - docker
install:
  - go get -u github.com/golang/lint/golint
  - make deps
  - cp tavle.tml.sample tavle.tml
script:
  - make dist
after_success:
  - if [ "x$TRAVIS_BRANCH" == "xmaster" ]; then
    docker build -t ryumei/tavle .
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push ryumei/tavle;
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lHiJjl+kahgYtKi6U284NttSIaVP1uhiTuGjr9msNyzf4mxUDKh12NPvQTyrQG8Qkt8X6wl9KWnIiI1lKheuniY1SWGWi8r5alanikwAgYxztbIL7AfKqjhc7QiKvKhfPskN1Q6hnzpTr+HNe5Yz7g6WAv82HGKFQ8NSxcnBqzzTtR+qf3qwlI7/jpKaxsbFZuzpIU9WUjzUlrE9XngCDpH2DD8K3+IZhpP1rzzDlFpuFsDyCklu0VSrJkSDvELS83OV6XDHL1G4tHRuBz+kPBbgnD5otzDawHPUkKuoFWsq7YdH1Xui7fV/v9DLXyt1dKB7vcr4nGyG93JqGsQz0UOm8x/MbF1qNux01Vp/OlNxb9rPWVQ02xRgOm1uuOsmW8Of32Wtf2shENWgCBNtPyS61Ll1V6D5KiyW9A7boUmZOeCR95oN5NfWqMirdYIyyIdAyt5IIIWDTFu+7hUD41XHaPbTWqyLX2zqnTKydXJMgxNtPWKpTcW8N8lX1M9W8vG4bO/3G7DhqQOl/0JiHw8fHD8aQ1PRl35IbAfpITzqsC+Fwn2g7EBZNy5/+C+tAv+24lUc0MXnUhgWBYfsUbYep9z+0D4HMWLRV0EWaH9eeXAWV6V0quCtmdv2U38Q8WGyy2rFPXHSCt/LrRTVlt2xrlMrzbfRo+4uQZdC1NM=
  file_glob: true
  file: dist/tavle-*amd64.zip
  on:
    repo: ryumei/tavle
    tags: true
    condition: x$TRAVIS_EVENT_TYPE != xcron
notifications:
  slack:
    secure: TpJtQjft0K64i1SLscypb5N6PJG+EupuIq+gDj4LGZoq5lsV3xs8AZpPWNpHGWb6+yhDT96zxAe2go7ZzMZvUIgAWiMrsKJikz5xEuHfUbvh5cqgbzFga1U432KUjEA+W2elzU0zP2kVUb8LPXyzPl0b8WCn8R4dZHeQ6Nkxksy3nsUm1IAKA5ET+zmtgFs9O0RWmgOowqj6dCEjZsGO3Dt3QKjPYRkmfqh3qvnoB+3+s68I+/xoNWUOwzGQnrVge8bqui/7GzEG1fiCmYkmfKENzCSgRrQumR8QrZDzzFmgu/43eL9s/xknP4kMVxCwUt5WE7BWAXuRVxIAKYxOhJkNllX9oy0ePtxnS/Fi2wgzkVUPKiRqTvNF/i1bNgrPQ94u/r+OV8f5QYfpkrRE/jD8w2XPWbR/Hgn9VPJpDZ5z/4rrYaPExyKS2KycaMDFPkjEAFqV7Wad+EIontZdM1JjA4PQGMxQWJ3DM3Fryd81vL/JCL7d94w48QzRZOfN6vxSAnNLJDSbEJXSx/iyeGloIvo9XMEIkauWlBhG4Yljvo5R4tYggawKvWIJeqiItHAsUvEJVsGQT+DfIkiyKgUI/L5KWKIlkFmgC/PgeFhbd87P0NdAyJwravvWiNsTmvT7HowvwImLZrKe3/SQRGQ02mMwZvv2/4NhrwYsR/s=
