language: go
go:
- 1.9
install:
- go get -u github.com/golang/lint/golint
- make deps
- cp tavle.tml.sample tavle.tml
script:
- make test
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: 'dist/tavle-*.{tar.gz,zip}'
  on:
    repo: ryumei/tavle
    tags: true
